//! Two jobs, both of them about a binary telling the truth about itself.
//!
//! 1. Make `option_env!("TMC_API_BASE")` honest. Cargo does not track the
//!    environment a crate was compiled in unless it is told to, so without that
//!    line changing `TMC_API_BASE` and rebuilding gives you the PREVIOUS base
//!    baked into an up-to-date-looking binary — the app quietly keeps talking
//!    to whichever site it was first built against, and the only cure is
//!    `cargo clean`.
//!
//! 2. Compile the shipped rules INTO the binary — both the app rules
//!    (`plugins/app/<slug>/…`) and the mod-manager descriptors
//!    (`plugins/manager/*.json`).
//!    They were Tauri resources in every design that came before this one, and
//!    a resource is a separate file next to the exe — which the portable
//!    Windows build does not carry, and a copied-somewhere-else AppImage does
//!    not either. A build with no rules is not a build with fewer games: it is
//!    one where detection finds nothing, no game can be launched, no sandbox
//!    knows its strategy and the config editor has nothing to list, all
//!    silently. That is too much to hang on a file being adjacent.
//!
//!    The rules stay FILES in the repository — this only reads them. Anything
//!    the user drops in `<data>/plugins/app/` still overrides what is compiled
//!    in, per game, and `<data>/plugins/manager/` does the same per manager.
//!
//!    The manager descriptors are here for the same reason and not a weaker
//!    one: a build that shipped none would offer an EMPTY list of mod managers
//!    to import from, which reads as "you have none installed" rather than as
//!    "this build forgot them".

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-env-changed=TMC_API_BASE");

    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    // `core/` → `src-tauri/` → repo root.
    let rules = manifest.join("../../plugins/app");

    let mut files = Vec::new();
    collect(&rules, &rules, &mut files);
    files.sort();

    // Rerun on the DIRECTORY as well as on each file: watching only the files
    // that exist means adding a game's first rule does not trigger a rebuild,
    // and the new game is missing from a binary that looks current.
    println!("cargo:rerun-if-changed={}", rules.display());
    for (_, path) in &files {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    let mut out = String::from(
        "// Generated by build.rs from <repo>/plugins/app. Do not edit.\n\
         pub(crate) static BUILTIN_APP_RULES: &[(&str, &str)] = &[\n",
    );

    for (rel, path) in &files {
        writeln!(
            out,
            "    ({:?}, include_str!({:?})),",
            rel,
            path.display().to_string()
        )
        .unwrap();
    }

    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    std::fs::write(out_dir.join("builtin_app_rules.rs"), out)
        .expect("could not write builtin_app_rules.rs");

    managers(&manifest, &out_dir);
}

/// The same treatment for `plugins/manager/*.json`, which is a FLAT directory —
/// a manager descriptor is one file and is not per-game.
fn managers(manifest: &Path, out_dir: &Path) {
    let dir = manifest.join("../../plugins/manager");

    println!("cargo:rerun-if-changed={}", dir.display());

    let mut files = Vec::new();

    if let Ok(entries) = std::fs::read_dir(&dir) {
        for entry in entries.flatten() {
            let path = entry.path();

            if entry.file_type().is_ok_and(|t| t.is_symlink()) {
                continue;
            }

            if !entry.metadata().is_ok_and(|m| m.is_file()) {
                continue;
            }

            let name = entry.file_name().to_string_lossy().into_owned();
            let lower = name.to_ascii_lowercase();

            if !(lower.ends_with(".json") || lower.ends_with(".yaml") || lower.ends_with(".yml")) {
                continue;
            }

            println!("cargo:rerun-if-changed={}", path.display());

            files.push((name, path));
        }
    }

    files.sort();

    let mut out = String::from(
        "// Generated by build.rs from <repo>/plugins/manager. Do not edit.\n\
         pub(crate) static BUILTIN_MANAGERS: &[(&str, &str)] = &[\n",
    );

    for (name, path) in &files {
        writeln!(
            out,
            "    ({:?}, include_str!({:?})),",
            name,
            path.display().to_string()
        )
        .unwrap();
    }

    out.push_str("];\n");

    std::fs::write(out_dir.join("builtin_managers.rs"), out)
        .expect("could not write builtin_managers.rs");
}

/// Every rule file under `plugins/app/`, as (slug-relative path, absolute path).
///
/// Extensions are not filtered here — `parse_source` decides what it
/// understands, and a file this ignored would be one the on-disk loader still
/// reads, which is exactly the kind of difference that makes a bug reproduce on
/// one machine and not the other.
fn collect(base: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };

    for entry in entries.flatten() {
        let path = entry.path();

        // Same rule the on-disk loader follows, for the same reason: a symlink
        // is a way to pull a file in from outside the tree.
        let Ok(meta) = entry.metadata() else { continue };
        if entry.file_type().is_ok_and(|t| t.is_symlink()) {
            continue;
        }

        if meta.is_dir() {
            collect(base, &path, out);
            continue;
        }

        if let Ok(rel) = path.strip_prefix(base) {
            // Forward slashes on every platform: this string becomes a rule's
            // `source`, which is shown in the UI and compared in tests.
            let rel = rel
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");

            out.push((rel, path));
        }
    }
}
